.PHONY: all tresenraya cuatroenlinea

all: tresenraya cuatroenlinea

tresenraya:
	gcc -O3 -o tresenraya main.c minmax.c tresenraya.c

cuatroenlinea:
	gcc -O3 -o cuatroenlinea main.c minmax.c cuatroenlinea.c
